let config;let selected=new Set();const form=document.querySelector("#configForm");const statusEl=document.querySelector("#status");
let pendingSave=Promise.resolve(true);
async function init(){config=await fetch("/api/config").then(r=>r.json());selected=new Set(config.whatsappGroups||[]);for(const[key,value]of Object.entries(config)){const field=form.elements.namedItem(key);if(!field)continue;if(field.type==="checkbox")field.checked=value;else field.value=value}await loadChats();await loadDigest();poll()}
let chatLabels=new Map();async function loadChats(){const discovered=await fetch("/api/discovered").then(r=>r.json());chatLabels=new Map(discovered.map(chat=>typeof chat==="string"?[chat,chat]:[chat.name,chat.label]));for(const name of selected)if(!chatLabels.has(name))chatLabels.set(name,name);renderChats()}
function renderChats(){const query=document.querySelector("#chatFilter").value.trim().toLowerCase();const all=[...chatLabels].filter(([,label])=>label.toLowerCase().includes(query)).sort((a,b)=>a[1].localeCompare(b[1]));const list=document.querySelector("#chatList");list.innerHTML=all.length?"":'<p class="muted">No matching chats.</p>';for(const[name,display]of all){const label=document.createElement("label");label.className="chat";const input=document.createElement("input");input.type="checkbox";input.checked=selected.has(name);input.onchange=()=>{input.checked?selected.add(name):selected.delete(name);renderSelected();queueSave()};label.append(input,document.createTextNode(display));list.append(label)}renderSelected()}
function renderSelected(){const box=document.querySelector("#selectedChats");box.innerHTML=selected.size?"":'<span class="muted">No groups selected.</span>';for(const name of selected){const chip=document.createElement("span");chip.className="selected-chip";const remove=document.createElement("button");remove.type="button";remove.textContent="×";remove.onclick=()=>{selected.delete(name);renderChats();queueSave()};chip.append(document.createTextNode(chatLabels.get(name)||name),remove);box.append(chip)}}
document.querySelector("#chatFilter").oninput=renderChats;
async function saveConfig(){const data=Object.fromEntries(new FormData(form));const secrets={openrouterKey:data.openrouterKey,resendKey:data.resendKey};delete data.openrouterKey;delete data.resendKey;for(const name of["headless","dryRun","redactPhoneNumbers","sendDigestEvenIfNoImportantMessages"])data[name]=form.elements.namedItem(name).checked;data.maxMessagesPerGroup=Number(data.maxMessagesPerGroup);data.scanLookbackHours=Number(data.scanLookbackHours);data.whatsappGroups=[...selected];data.browserProfilePath=config.browserProfilePath;data.databasePath=config.databasePath;const response=await fetch("/api/config",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});if(secrets.openrouterKey||secrets.resendKey){await fetch("/api/secrets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(secrets)});form.elements.namedItem("openrouterKey").value="";form.elements.namedItem("resendKey").value=""}statusEl.textContent=response.ok?"Configuration saved":"Save failed";return response.ok}
function queueSave(){statusEl.textContent="Saving group selection…";pendingSave=pendingSave.then(()=>saveConfig(),()=>saveConfig());return pendingSave}
form.onsubmit=async e=>{e.preventDefault();await queueSave()};
document.querySelector("#addChat").onclick=async()=>{const input=document.querySelector("#manualChat");if(input.value.trim()){selected.add(input.value.trim());chatLabels.set(input.value.trim(),input.value.trim())}input.value="";renderChats();await queueSave()};document.querySelector("#refreshChats").onclick=loadChats;
async function loadDigest(){const digest=await fetch("/api/latest-digest").then(r=>r.json());document.querySelector("#digestPreview").textContent=digest?.markdown||"No digest generated yet."}
document.querySelector("#refreshDigest").onclick=loadDigest;
document.querySelectorAll("[data-run]").forEach(button=>button.onclick=async()=>{if(button.dataset.run==="clear"&&!confirm("Delete all locally stored messages?"))return;if(["scan","digest","job"].includes(button.dataset.run))await queueSave();const response=await fetch(`/api/run/${button.dataset.run}`,{method:"POST"});const result=await response.json();statusEl.textContent=result.status||result.error});
let previousStatus="";async function poll(){try{const value=await fetch("/api/status").then(r=>r.json());statusEl.textContent=value.status;statusEl.classList.toggle("busy",value.busy);document.querySelectorAll("[data-run]").forEach(b=>b.disabled=value.busy);if(!value.busy&&value.status==="discover completed")await loadChats();if(!value.busy&&value.status!==previousStatus&&(value.status==="digest completed"||value.status==="job completed"))await loadDigest();previousStatus=value.status}finally{setTimeout(poll,1500)}}init();
